### PR TITLE
Clean the dataset

### PR DESCRIPTION
**Pull request by nestornav**
This PR aims to solve the issue #1.  Provide a notebook using pandas and python as manipulation tool.

Also add a brief readme with instructions to start working.

### CODE REVIEW

**Comment by Emekaborisama** [comment]
Hello @nestornav Kindly remove the "Twitter" from Tweet source

**Review by Emekaborisama — CHANGES_REQUESTED** [review]
Remove "Twitter" from tweet source

**Comment by nestornav** [comment]
@Emekaborisama the change was done!

**Review by Emekaborisama — APPROVED** [review]
Awesome.

**Pull request merged**
