### PR TITLE
creates clean dataset for Sex4Grades

### PR DESCRIPTION
**Pull request by lornamariak**
Cleaned the Sex4Grades csv.
😬Just realised I was working in the master.

### CODE REVIEW

**Comment by Emekaborisama** [comment]
@lornamariak OMG, You did a Good job with R, Kindly submit the cleaned dataset in CSV format You can create a pull request and submit the dataset

**Comment by Emekaborisama** [comment]
You should Fork the repo next time and work with your branch

**Comment by lornamariak** [comment]
> You should Fork the repo next time and work with your branch

literally realised this after pushing 🙂super sorry.

**Review by Emekaborisama — COMMENTED** [review]
Submit the cleaned dataset on csv format

**Pull request merged**
